"""rr-planner static validator package."""

from __future__ import annotations

from .checks import (
    check_drift,
    check_kind_and_children,
    check_numbering,
    check_parents,
    check_required_fields,
    check_revive,
    check_status,
    check_unique_and_ids,
)
from .cli import main
from .constants import (
    AGENT_CONFIG_PATH,
    AGENT_PLAN_NAME,
    AGENT_PLAN_TEMPLATE_PATH,
    BUILD_VALUES,
    CLASS_VALUES,
    DOC_STEMS,
    FUTURE_NAME,
    KANO_VALUES,
    KIND_VALUES,
    MAGNITUDE_VALUES,
    MINT_EXCLUDED_KEYS,
    MOSCOW_VALUES,
    PARENT_DOC,
    PREFIX_TO_DOC,
    SCHEMA_PATH,
    SETUP_SECTIONS,
    SPEC_VALUES,
)
from .ledger import check_rationale, load_ledger
from .models import Axis, Issue, Item, Triad, has_errors
from .parse import (
    derived_class,
    detect_doc_format,
    parse_inline_meta_line,
    parse_markdown,
    parse_planning_dir,
    parse_yaml_doc,
)
from .rewrite import format_meta_line
from .setup import (
    emit_agent_plan,
    parse_agent_config,
    sync_agent_injection,
    sync_root_sot,
)
from .validate import validate_dir
from .workspace import (
    accept_challenge_residual,
    canonical_mint_payload,
    check_baselines,
    compute_doc_digest,
    compute_mint_hash,
    default_unfrozen_status,
    fill_status_missing,
    find_status_path,
    has_cascade_docs,
    invalidate_challenge_on_compose,
    invalidate_challenge_on_digest_change,
    load_status,
    parse_frontmatter,
    stamp_challenge_status,
    write_status_yaml,
)

__all__ = [
    "AGENT_CONFIG_PATH",
    "AGENT_PLAN_NAME",
    "AGENT_PLAN_TEMPLATE_PATH",
    "BUILD_VALUES",
    "CLASS_VALUES",
    "DOC_STEMS",
    "FUTURE_NAME",
    "KANO_VALUES",
    "KIND_VALUES",
    "MAGNITUDE_VALUES",
    "MINT_EXCLUDED_KEYS",
    "MOSCOW_VALUES",
    "PARENT_DOC",
    "PREFIX_TO_DOC",
    "SCHEMA_PATH",
    "SETUP_SECTIONS",
    "SPEC_VALUES",
    "Axis",
    "Issue",
    "Item",
    "Triad",
    "accept_challenge_residual",
    "canonical_mint_payload",
    "check_baselines",
    "check_drift",
    "check_kind_and_children",
    "check_numbering",
    "check_parents",
    "check_rationale",
    "check_required_fields",
    "check_revive",
    "check_status",
    "check_unique_and_ids",
    "compute_doc_digest",
    "compute_mint_hash",
    "default_unfrozen_status",
    "derived_class",
    "detect_doc_format",
    "emit_agent_plan",
    "fill_status_missing",
    "find_status_path",
    "format_meta_line",
    "has_cascade_docs",
    "has_errors",
    "invalidate_challenge_on_compose",
    "invalidate_challenge_on_digest_change",
    "load_ledger",
    "load_status",
    "main",
    "parse_agent_config",
    "parse_frontmatter",
    "parse_inline_meta_line",
    "parse_markdown",
    "parse_planning_dir",
    "parse_yaml_doc",
    "stamp_challenge_status",
    "sync_agent_injection",
    "sync_root_sot",
    "validate_dir",
    "write_status_yaml",
]
